name: cd dev
# Controls when the workflow will run
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Contineous-Integration"]
    types: 
      - completed
    
permissions:
  id-token: none
  contents: read


jobs:  
  cd_devl_build:    
    runs-on: ubuntu-latest
    name: cd devl build
    steps:      
      - uses: actions/checkout@v3
        name: Git checkout

      # Runs a single command using the runners shell
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
        #run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Build & Analysis
        env:
          projectName: ${{ inputs.sonar_projectName }}
        run: |
          echo Add other actions to build,
          echo project name is $projectName
