name: Multi-Job Workflow
on:
  workflow_dispatch:
permissions:
    contents: read
    id-token: write
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 Step
        run: echo "Running Job 1"

  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: Job 2 Step
        run: echo "Running Job 2"

  job-3:
    needs: approval-job-2
    runs-on: ubuntu-latest
    steps:
      - name: Job 3 Step
        run: echo "Running Job 3"

  approval-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approval
        id: check_approval
        run: |
          if: [[ "${{ github.event_name }}" == "pull_request" ]] &&
             [[ "$(jq -r '.pull_request.user.login' <<< $GITHUB_EVENT_PATH)" == "prashantkatare" ]]; then
            echo "Approval granted."
            echo "::set-output name=approved::true"
          else
            echo "Approval not granted."
            echo "::set-output name=approved::false"
          fi

  approve-job-2:
    needs: job-2
    runs-on: ubuntu-latest
    if: needs.approval-job-2.outputs.approved == 'true'
    steps:
      - name: Approve Job 2
        run: echo "Job 2 approved"
