name: Sonar-Scan
# Controls when the workflow will run
on: 
  workflow_call:
    inputs:
      sonar_projectName:
        type: string
        description: Enter project name
        required: true
permissions:
  id-token: none
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Sonarqube_scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: SonarQube Scan

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
        #run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Build & Analysis
        env:
          projectName: ${{ inputs.sonar_projectName }}
        run: |
          echo Add other actions to build,
          echo project name is $projectName
